unifi folders

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -1,6 +1,5 @@
 ---
 name: Build Documentation
-
 on:
   push:
     branches: [main]
@@ -22,69 +21,68 @@ on:
       - pyproject.toml
 
 jobs:
-  Docs:
-    name: linux docs
-    runs-on: ubuntu-latest
-    env:
-      DOC_VERSION: dev
+  test-docs:
     defaults:
       run:
         shell: bash -l {0}
-    concurrency:
-      group: ${{ github.workflow }}-${{ github.ref }}
-      cancel-in-progress: true
-    timeout-minutes: 15
+    env:
+      DOC_PYTHON_VERSION: '3.11'
+    runs-on: ubuntu-latest
     steps:
       - name: checkout code
         uses: actions/checkout@v3
 
-      - name: Setup Mambaforge
-        uses: conda-incubator/setup-miniconda@v2
-        with:
-            python-version: 3.11
-            miniforge-variant: Mambaforge
-            miniforge-version: latest
-            channels: conda-forge
-            activate-environment: hydromt
-            use-mamba: true
+      # we need environment.yml to see if we have a cache hit
       - name: Generate env spec
-        run: python make_env.py doc
+        run: pip install tomli && python make_env.py test,io,extra,doc -p ${{ env.DOC_PYTHON_VERSION }} -n hydromt
 
-
-      - name: Set cache date
-        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
-
-      - name: load from cache if it exists for our environment
-        uses: actions/cache@v3
-        with:
-          path: /usr/share/miniconda3/envs/hydromt
-          key: docs-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}
+      - name: load from cache
         id: cache
+        uses: actions/cache/restore@v3
+        with:
+          path: |
+            /usr/share/miniconda3
+            ~/pycache
+            ~/docs/_build
+          # the below two settings mean we'll alway srestore the cache
+          # but the cache hit output can tell us if we have to update afterwards
+          key: docs-${{ hashFiles('environment.yml')  }}
+          restore-keys: |
+            docs
 
-      - name: Update environment & write to cache
-        run: mamba env update -n hydromt -f environment.yml
+      - name: Fail on no cache restore
+        if: steps.cache.outputs.cache-matched-key == ''
+        run: |
+          echo "Failed to restore any cache. exiting..."
+          exit 1
+
+      # by avoiding the mamba setup stage by loading it from cache instead we save
+      # a lot of setup time, but we do have to do our own PATH management
+      # hence the exports
+      - name: Update environment
         if: steps.cache.outputs.cache-hit != 'true'
+        run: |
+          export PATH=/usr/share/miniconda3/bin:$PATH
+          mamba env update -n hydromt -f environment.yml
 
-      - name: Install hydromt
-        run: pip install .
-
-      - name: test docs
+      # if we're not publishing we don't have to write them, so we might as well
+      # save ourself a bunch of IO time
+      - name: Generate dummy docs
         if: ${{ github.event_name == 'pull_request' }}
         run: |
-          make html_test
+          export PATH=/usr/share/miniconda3/bin:$PATH
+          PYTHONPYCACHEPREFIX=~/pycache mamba run -n hydromt sphinx-build docs/source docs/_build -b dummy
 
-      - name: Build docs
+      - name: Generate docs
         if: ${{ github.event_name != 'pull_request' && !github.event.act }}
         run: |
-          make html
-
-
-      - name: Set doc version
-        run: echo "DOC_VERSION=$(python -c 'from hydromt import __version__ as v; print("dev" if "dev" in v else "v"+v.replace(".dev",""))')" >> $GITHUB_ENV
+          export PATH=/usr/share/miniconda3/bin:$PATH
+          PYTHONPYCACHEPREFIX=~/pycache mamba run -n hydromt sphinx-build docs/source docs/_build
+          echo "DOC_VERSION=$(python -c 'from hydromt import __version__ as v; print("dev" if "dev" in v else "v"+v.replace(".dev",""))')" >> $GITHUB_ENV
 
       - name: Upload to GitHub Pages
         if: ${{ github.event_name != 'pull_request' && !github.event.act }}
-        uses: peaceiris/actions-gh-pages@v3.8.0
+        uses: peaceiris/actions-gh-pages@v3.9.3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./docs/_build/html
diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -17,6 +17,7 @@ on:
       - data/*
       - pyproject.toml
 
+
 jobs:
   build:
     defaults:
@@ -36,22 +37,39 @@ jobs:
 
       - uses: actions/checkout@v3
 
+      # we need environment.yml to see if we have a cache hit
+      - name: Generate env spec
+        run: pip install tomli && python make_env.py test,io,extra -p ${{ matrix.python-version}} -n hydromt
+
       - name: load from cache
+        id: cache
         uses: actions/cache/restore@v3
         with:
-          path: /usr/share/miniconda3/envs/hydromt
-          key: ${{ matrix.python-version }}
+          path: |
+            /usr/share/miniconda3
+            ~/pycache
+          # the below two settings mean we'll alway srestore the cache
+          # but the cache hit output can tell us if we have to update afterwards
+          key: test-py${{ matrix.python-version }}-${{ hashFiles('environment.yml')  }}
+          restore-keys: |
+            test-py${{ matrix.python-version }}
 
-      # tomli should be installed in cache already
-      - name: Generate env spec
-        run: mamba run -n hydromt python make_env.py test,io,extra -p ${{ matrix.python-version}} -n hydromt
+      - name: Fail on no cache restore
+        if: steps.cache.outputs.cache-matched-key == ''
+        run: |
+          echo "Failed to restore any cache. exiting..."
+          exit 1
 
-      # since we all just load from one cache now, we always update the environment
+      # by avoiding the mamba setup stage by loading it from cache instead we save
+      # a lot of setup time, but we do have to do our own PATH management
+      # hence the exports
       - name: Update environment
-        run: mamba env update -n hydromt -f environment.yml
+        if: steps.cache.outputs.cache-hit != 'true'
+        run: |
+          export PATH=/usr/share/miniconda3/bin:$PATH
+          mamba env update -n hydromt -f environment.yml
 
       - name: Test
-        run: mamba run -n hydromt python -m pytest --verbose --cov=hydromt --cov-report xml
-
-      - name: Upload code coverage
-        uses: codecov/codecov-action@v3
+        run: |
+          export PATH=/usr/share/miniconda3/bin:$PATH
+          PYTHONPYCACHEPREFIX=~/pycache mamba run -n hydromt python -m pytest --verbose --cov=hydromt --cov-report xml
