update prep-release workflow

diff --git a/.github/workflows/prep-release.yml b/.github/workflows/prep-release.yml
--- a/.github/workflows/prep-release.yml
+++ b/.github/workflows/prep-release.yml
@@ -51,38 +51,44 @@ jobs:
         run: |
 
           set -e
-          # check if there already is a release PR open
-          # parsing of current version
-          export CURRENT_VERSION=$(grep "__version__" hydromt/__init__.py | cut -d= -f 2 | tr -d "\" ")
-          export CURRENT_MAJOR=$(echo $CURRENT_VERSION | cut -d'.' -f 1)
-          export CURRENT_MINOR=$(echo $CURRENT_VERSION | cut -d'.' -f 2)
-          export CURRENT_PATHCH=$(echo $CURRENT_VERSION | cut -d'.' -f 3)
 
+          # Detect whether the current version is a pre-release (dev/rc/alpha/beta)
+          export IS_PRERELEASE=false
+          if grep -q "__version__" hydromt/__init__.py | grep -qE '(\.dev|rc)'; then
+            export IS_PRERELEASE=true
+          fi
+
+          # Strip any pre-release suffix (e.g. 1.4.0.dev0 -> 1.4.0, 1.4.0rc1 -> 1.4.0)
+          export BASE_VERSION=$(echo $CURRENT_VERSION | sed 's/\.dev[0-9]*//' | sed 's/rc[0-9]*//' | sed 's/a[0-9]*//' | sed 's/b[0-9]*//')
+
+          export CURRENT_MAJOR=$(echo $BASE_VERSION | cut -d'.' -f 1)
+          export CURRENT_MINOR=$(echo $BASE_VERSION | cut -d'.' -f 2)
+          export CURRENT_PATCH=$(echo $BASE_VERSION | cut -d'.' -f 3)
+
+
+          ## Calculate new release version number.
+          ## If the current version is already a pre-release of the next minor/major
+          ## (e.g. 1.4.0.dev0 or 1.4.0rc1) and the bump matches, finalise that
+          ## version instead of bumping again.
           BUMP=$BUMP_KIND
 
-          ## calculate new release number
           case $BUMP in
-
-          "same")
-          	export NEW_VERSION="$CURRENT_MAJOR.$CURRENT_MINOR.$CURRENT_PATHCH"
-          	;;
-
-          "patch")
-          	export NEW_VERSION="$CURRENT_MAJOR.$CURRENT_MINOR.$((CURRENT_PATHCH + 1))"
-          	;;
-
-          "minor")
-          	export NEW_VERSION="$CURRENT_MAJOR.$(($CURRENT_MINOR + 1)).0"
-          	;;
-
-          "major")
-          	export NEW_VERSION="$((CURRENT_MAJOR + 1)).0.0"
-          	;;
-          *)
-          	echo "invalid bump: $BUMP"
-          	exit 1
-          	;;
+            "minor")
+              export NEW_MAJOR=$CURRENT_MAJOR
+              export NEW_MINOR=$(($CURRENT_MINOR + 1))
+              ;;
+            "major")
+              export NEW_MAJOR=$((CURRENT_MAJOR + 1))
+              export NEW_MINOR=0
+              ;;
+            *)
+              echo "invalid bump: $BUMP"
+              exit 1
+              ;;
           esac
+
+          export NEW_VERSION="$NEW_MAJOR.$NEW_MINOR.0"
+          export RELEASE_BRANCH="release/$NEW_MAJOR.$NEW_MINOR"
 
           ## setting up git
           git config user.name "GitHub Actions Bot"
@@ -90,15 +96,14 @@ jobs:
 
           ## create release branch
           git pull # make sure git doesn't reject our push because of unknown refs
-          git checkout -b "release/v$NEW_VERSION"
+          git checkout -b "$RELEASE_BRANCH"
 
           # update version in python file
           sed -i "s/.*__version__.*/__version__ = \"$NEW_VERSION\"/" hydromt/__init__.py
 
+          # update changelog with new header
           export NEW_CHANGELOG_HEADER="v$NEW_VERSION ($(date -I))"
           export NEW_HEADER_UNDERLINE=$(printf '=%.0s' $(seq 1 $(echo $NEW_CHANGELOG_HEADER | awk '{print length}')))
-
-          # update changelog with new header
           sed -i "/Unreleased/{s/Unreleased/$NEW_CHANGELOG_HEADER/;n;s/=*/$NEW_HEADER_UNDERLINE/}" docs/changelog.rst
 
           # update switcher.json while maintaining the correct order with some black jq incantations. I'll try and explain below
@@ -126,14 +131,14 @@ jobs:
 
           git add .
           git commit -m "prepare for release v$NEW_VERSION"
-          git push --set-upstream origin "release/v$NEW_VERSION"
+          git push --set-upstream origin "$RELEASE_BRANCH"
 
           # gh cli should return the url of the pr it just created. we'll store that so we can access it later
           # regarding the comment about limitations: currently in github you can only base triggers on the base/target branch name
           # not the branch that the PR is from. You can circumvent this with an if condition, but that would mean this workflow
           # would run under every PR which I don't like, so for now this has to be a manual step.
-          export PR_URL=$( gh pr create -B "main" -H "release/v$NEW_VERSION" -t "Release v$NEW_VERSION" -b "Hi there! This is an automated PR made for your release. Pushing commits to this branch will start the creation and testing of release artifacts. Due to limitations with github actions I can't start these for you but you can do so by adding an empty commit with `git commit --allow-empty`. Once the release artifacts are ready I'll comment links to them so you can inspet them. Please check that the PR is as you would like it to be, and feel free to push any changes to this branch before merging.  Once you're happy with the state of the PR, just merge the PR (I recommend squashing, partially because the empty commits you might have had to add), and run the `.github/workflows/finish-release.yml` workflow. (Due to Github limitations I can't do this for you, but my creator is working on a solution)" )
-          gh co "release/v$NEW_VERSION"
+          export PR_URL=$( gh pr create -B "main" -H "$RELEASE_BRANCH" -t "Release v$NEW_VERSION" -b "Hi there! This is an automated PR made for your release. Pushing commits to this branch will start the creation and testing of release artifacts. Due to limitations with github actions I can't start these for you but you can do so by adding an empty commit with \`git commit --allow-empty\`. Once the release artifacts are ready I'll comment links to them so you can inspet them. Please check that the PR is as you would like it to be, and feel free to push any changes to this branch before merging.  Once you're happy with the state of the PR, just merge the PR (I recommend squashing, partially because the empty commits you might have had to add), and run the \`.github/workflows/finish-release.yml\` workflow. (Due to Github limitations I can't do this for you, but my creator is working on a solution)" )
+          gh co "$RELEASE_BRANCH"
 
           # not fetched by default
           git fetch --tags
@@ -149,5 +154,4 @@ jobs:
             echo $'\n\n```\n' >> comment.txt
             echo "(you might have to update the receipt to update to reflect these changes when releasing to conda)"
             gh pr comment "$PR_URL" --body-file comment.txt
-
           fi
