fix docker build (#1333)
Co-authored-by: Marnix <150045289+deltamarnix@users.noreply.github.com>

diff --git a/.github/workflows/test-docker.yml b/.github/workflows/test-docker.yml
--- a/.github/workflows/test-docker.yml
+++ b/.github/workflows/test-docker.yml
@@ -5,13 +5,15 @@ on:
   push:
     branches: [main]
     paths:
-      - .binder/*
+      - .github/workflows/test-docker.yml
+      - .binder/**
       - Dockerfile
       - pyproject.toml
   pull_request:
     branches: [main]
     paths:
-      - .binder/*
+      - .github/workflows/test-docker.yml
+      - .binder/**
       - Dockerfile
       - pyproject.toml
 
@@ -25,19 +27,40 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v6
-      - name: Build slim
-        uses: docker/build-push-action@v6
-        with:
-          context: .
-          target: slim
-          tags: deltares/hydromt:slim
-          load: true
-          build-args: |
-            PIXIENV=slim-latest
-      - name: Test Binder integration with repo2docker
+      - uses: prefix-dev/setup-pixi@v0.9.3
+      - name: Set up Docker
+        uses: docker/setup-docker-action@v4
+      - name: Build actual binder image
+        run: pixi run docker-build-binder
+      - name:
+        id: test-image
         run: |
-          pip install jupyter-repo2docker
-          repo2docker . echo 'success!'
+          # actually fail when something goes wrong
+          set -e
+
+          # run the docker image detached, it will start the jupyter server for us
+          docker run -d -p 8888:8888 deltares/hydromt:binder
+
+          # give it a second or two to start up
+          sleep 10
+
+          # check if we can reach the server
+          curl -f "http://localhost:8888/api/"
+
+      # only show logs if previous step failed
+      - name: show logs
+        if: failure()
+        run: |
+          echo "# Containers:"
+          docker container ls
+
+          echo "# Logs:"
+          docker logs "$(docker container ls -q)"
+
+
+
+
+
   test-docker:
     runs-on: ubuntu-latest
     concurrency:
